### ISSUE TITLE
*.mediaset.it/.net whitelist

### ISSUE THREAD

**Issue by jawz101** [bigdargon/hostsVN#156]
Hello, I just wanted to pass along an issue reported to me in this issue https://github.com/AdAway/adaway.github.io/issues/47

it looks like these domains cause some breakage with televisions

```
enabler.datalake.mediaset.it
hbbtv.mediaset.net
webtrekk.mediaset.net
```

thank you

**Comment by spirillen** [comment]
Hi @jawz101 and @bigdargon I would actually say the opposed, as the [original request](https://www.mypdns.org/ticket/65) is to get them blocked. 

For what I can read from various posts and comments however, it seems like, from nobody to a very limited sets of people, actually knows what these domains is used to, and why they originally have been added to a blacklists.

But neither I or @AnonymousPoster knows what they are used for nor it will brakes more than helping by adding the domains `enabler.datalake.mediaset.it` and `hbbtv.mediaset.net` to the DNS firewall matrix.

The core problem can arise if the common people needs this is the same disgusting way as ~~google~~ to get there zombie TV to view whatever they believe they needs.

The remaining real question, as I see it, is whether to block these two domains or not, since it appears to be a common opinion on blocking `webtrekk.mediaset.net`

**Comment by bigdargon** [comment]
Thanks @jawz101. In the past, I built lists based on existing lists. Currently, I am optimizing the blocking list such as removing low access domain names in Vietnam. For Steven Black's project, I only combine advertising/tracking domains in Vietnam ([link](https://github.com/bigdargon/hostsVN/blob/master/option/hosts-VN)). And I thank you for mentioning me to promptly fix it!
