### ISSUE TITLE
(DLEF) Domain list exchange format

### ISSUE THREAD

**Issue by spirillen** [bigdargon/hostsVN#292]
First of sorry, if I didn't pick the right template, but got lost in translation :smiley: 
![image](https://user-images.githubusercontent.com/44526987/115238764-56a9ee00-a11e-11eb-9b05-0e35955d02de.png)

I would like to hear if it would be possible to have you hosting and maintaining a DLEF formatted json file so I can generate an RPZ zone with your records.

To see a bit more about what the DLEF is, then @Somebodyisnobody has made a nice description of it here: https://www.mypdns.org/T3776 and with examples here: https://www.mypdns.org/P38 and https://www.mypdns.org/P39

There is already an initial import script by @Somebodyisnobody here https://github.com/matrix-rocks/chongluadao-jdk-import

## Alternative 1
Slit you records into two sublists which contains domains that should be blocked by wildcard and a lists which should only be blocked at specific level. IE: `badstuff.example.org`

## Alternative 2
Add the records straight into my lists at https://github.com/mypdns/matrix/tree/master/source

Looking forward to a reply and possible a collaboration between our blacklist projects.

**Comment by bigdargon** [comment]
> First of sorry, if I didn't pick the right template, but got lost in translation

No problem. I create templates so that Vietnamese can easily create reports. In the future, I will support English and Vietnamese in parallel.

> I would like to hear if it would be possible to have you hosting and maintaining a DLEF formatted json file so I can generate an RPZ zone with your records.

So sorry! I'm not studying information technology or programming. So creating other formats for me is very difficult.

> Slit you records into two sublists which contains domains that should be blocked by wildcard and a lists which should only be blocked at specific level. IE: `badstuff.example.org`

Currently, I support Adguard application, with this application can block wildcard. I split into 2 groups of domain names, one group is domain names (or servers) located in Vietnam, the other group is domain names (or servers) that are frequently accessed in Vietnam.

This is the group of domains (servers) in Vietnam, I put the wildcard in the optimized group. https://github.com/bigdargon/hostsVN/blob/master/source/adservers.txt
And the wildcard domains, I've listed the subdomains here, they are placed in the group tag https://github.com/bigdargon/hostsVN/blob/master/source/hosts-VN-group.txt

Similarly, with the domain names (servers) frequently accessed in Vietnam, I have https://github.com/bigdargon/hostsVN/blob/master/source/adservers-all.txt and https://github.com/bigdargon/hostsVN/blob/master/source/hosts-group.txt

**Comment by spirillen** [comment]
Took a quick look in your optimized list...

https://github.com/bigdargon/hostsVN/blob/46e0b5d6395f2625c1f8aaceed84e107c79d084f/source/adservers.txt#L16

Unfortunately there are these `*` wildcard :unamused: That is not DNS compatible :thinking: 

I'll mount my thinking hat and get back...

**Comment by bigdargon** [comment]
Such wildcard domain names block very well in applications such as Adguard, Adblock of FutureMind (I have contacted and the programmer has supported wildcard in version 4.2.1) and NextDNS service.

**Comment by spirillen** [comment]
They are still invalid DNS records :wink: 

Ping @Somebodyisnobody  Is this something we remembered to think of in the DLEF standard?

**Comment by bigdargon** [comment]
Maybe I'll close the issue here. If there are more updates, please open the issue again. Thank you!
