### ISSUE TITLE
Declining 16,000+ new gambling hosts

### ISSUE THREAD

**Issue by StevenBlack** [bigdargon/hostsVN#333]
Hi BigDargon @bigdargon!

I'm declining the 16,000+ new gambling hosts in this file...

   https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/gambling/hosts

... because 16,000 new hosts seems extreme and improbable. I tried several of the new domains and none of them resolved for me.

I'm very conscious that the size of hosts files matter, especially on Windows OS.

So I've paused refreshing the gambling hosts until you can comment.  See this commit here: https://github.com/StevenBlack/hosts/commit/b6040746986ce39812c81dacce20468fcc8d106b

Thanks!

**Comment by bigdargon** [comment]
Thanks @StevenBlack for the reminder! I'm going to split gambling and adult content into Vietnamese and non-Vietnamese languages, just like the ads/trackers I'm working on.

Currently, in my country, there are a lot of online gambling ads (among them are servers from China). Therefore, some users have requested/provided gambling domains data.

I will proceed to create a dead domain test repo using the dead-hosts project, in order to remove the domains that are no longer available. Give me a little time, I will ping you when the plan is complete!

**Comment by bigdargon** [comment]
@StevenBlack I'm done, waiting for the Push Request to be merged.
