### ISSUE TITLE
Force `tanx.com` to block lists instead of `p.tanx.com`?

### ISSUE THREAD

**Issue by fernvenue** [bigdargon/hostsVN#376]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:

Hi, seems `p.tanx.com` blocked currently, how about block `tanx.com` and all its sub domains instead of `p.tanx.com` only? Is there any reason why just `p.tanx.com` is blocked? I just found out that some domains like `kgb-ifs.tanx.com` may tracking users, so I think maybe block them all will be great. By the way, I can't speak Vietnamese, so sorry for this English issue.

**Comment by bigdargon** [comment]
@fernvenue Sorry for the delay!
- I block the domain `p.tanx.com` because it is a tracker. Refer to https://urlscan.io/search/#p.tanx.com
- I didn't block `tanx.com` because I'm not sure if this domain is a business domain or not?

Thank you for your information! I will pay attention to this domain and will block it if it is a tracker.

P/s: I can understand and answer in English.
